### ISSUE TITLE
Publish 0.1.5 to npm

### ISSUE THREAD

**Issue by davidgovea** [zzarcon/ember-cli-Mutation-Observer#12]
Hi @zzarcon - could you please `npm publish` the latest version? Thank you!

**Comment by zzarcon** [comment]
Hi @davidgovea !

Will you be interested on doing it yourself? I can give you publish access on npm and add you as collaborator on Github. Will be a good chance to improve the library, what do you think? :)

**Comment by davidgovea** [comment]
@zzarcon sure I'd be happy to. Same name on npm https://www.npmjs.com/~davidgovea

**Comment by zzarcon** [comment]
@davidgovea awesome! you are the boss now ;)

**Comment by davidgovea** [comment]
Thanks! and published..
