### ISSUE TITLE
Problems with ember cli 2.5

### ISSUE THREAD

**Issue by josephh** [zzarcon/ember-cli-Mutation-Observer#9]
Should this add on work with more recent versions of Ember?  I'm on ember cli 2.5 and see errors `ember.debug.js:32110 TypeError: container.lookupFactory is not a function` trying to use as a mixin.

**Comment by zzarcon** [comment]
Yes, this addon should work with recent version of ember-cli, can you please let me know which version of ember are you using? thanks!

**Comment by zzarcon** [comment]
@josephh Fixed on `0.1.4` version, please try it and let me know if works for you now, thanks!

**Comment by josephh** [comment]
Thanks for the reply. 'Fraid I haven't been able to test it yet, following the instructions and mixin example in the readme, my browser complains that is can't find the file to import (and I see I don't have a mixins folder in a location local to my component.js. (`import mutationObserver from '../mixins/mutation-observer';`)   

I've done the npm install.
